import { SlashCommandBuilder, MessageFlags } from 'discord.js';
import { createEmbed, errorEmbed } from '../../utils/embeds.js';
import { getLogChannel, EVENT_TYPES } from '../../services/loggingService.js';
import { snipeCache } from '../../utils/snipeCache.js';
import { InteractionHelper } from '../../utils/interactionHelper.js';

export default {
  data: new SlashCommandBuilder()
    .setName("snipe")
    .setDescription("Shows deleted messages")
    .addIntegerOption((option) =>
      option
        .setName("when")
        .setDescription("Type a number (eg- 2 for the second recent deleted message and 3 for third and so on..).")
        .setMinValue(1)
        .setMaxValue(20)
        .setRequired(false)
    ),
  category: "utility",

  // --- SLASH COMMAND EXECUTION ---
  async execute(interaction, config, client) {
    const deferSuccess = await InteractionHelper.safeDefer(interaction, {
      flags: MessageFlags.Ephemeral,
    });
    if (!deferSuccess) return;

    const index = interaction.options.getInteger("when") ?? 1;
    const embed = await getSnipeEmbed(client, interaction.guild, interaction.channel, index);

    await InteractionHelper.safeEditReply(interaction, {
      embeds: [embed],
      flags: MessageFlags.Ephemeral,
    });
  },

  // --- PREFIX COMMAND EXECUTION (!snipe / !snipe <number>) ---
  async runPrefix(message, args) {
    const parsedIndex = parseInt(args[0], 10);
    const index = !isNaN(parsedIndex) && parsedIndex > 0 ? parsedIndex : 1;

    const embed = await getSnipeEmbed(message.client, message.guild, message.channel, index);
    await message.reply({ embeds: [embed] });
  }
};

/**
 * Retrieves the appropriate snipe embed based on log channel availability or RAM cache.
 */
async function getSnipeEmbed(client, guild, targetChannel, position) {
  const logChannel = await getLogChannel(client, guild.id, EVENT_TYPES.MESSAGE_DELETE);

  // --- PATH A: Server HAS a Log Channel (Fetch from Log Channel Messages) ---
  if (logChannel) {
    try {
      const logs = await logChannel.messages.fetch({ limit: 100 });

      // Filter logs generated by loggingService for this specific channel
      const channelLogs = logs.filter((msg) => {
        if (!msg.embeds.length) return false;
        const embed = msg.embeds[0];
        const isDeleteAction = embed.title?.toLowerCase().includes("message deleted");
        const isThisChannel = embed.description?.includes(targetChannel.id) || 
                              embed.fields?.some(f => f.value.includes(targetChannel.id));
        return isDeleteAction && isThisChannel;
      });

      const logsArray = Array.from(channelLogs.values());
      const arrayIndex = position - 1;

      if (logsArray.length === 0) {
        return errorEmbed("Nothing to Snipe", "No recently deleted messages found in the log channel for this channel.");
      }

      if (arrayIndex >= logsArray.length) {
        return errorEmbed("Snipe Out of Range", `Only **${logsArray.length}** deleted message(s) are logged for this channel.`);
      }

      const logMsg = logsArray[arrayIndex];
      const logEmbed = logMsg.embeds[0];

      const embed = createEmbed()
        .setAuthor({
          name: logEmbed.author?.name || "Deleted Message",
          iconURL: logEmbed.author?.iconURL
        })
        .setDescription(logEmbed.description || logEmbed.fields?.find(f => f.name === "Message")?.value || "*[No content]*")
        .addFields(
          { name: "Source", value: "Fetched from Log Channel", inline: true },
          { name: "Position", value: `#${position} of ${logsArray.length}`, inline: true }
        )
        .setFooter({ text: `Requested position #${position}` })
        .setTimestamp(logMsg.createdAt);

      if (logEmbed.image) embed.setImage(logEmbed.image.url);

      return embed;
    } catch (err) {
      // Fall through to memory cache if log channel fetch fails
    }
  }

  // --- PATH B: Server HAS NO Log Channel (Fallback to RAM Cache) ---
  const channelSnipes = snipeCache.get(targetChannel.id);

  if (!channelSnipes || channelSnipes.length === 0) {
    return errorEmbed("Nothing to Snipe", "No recently deleted messages found in memory for this channel.");
  }

  const arrayIndex = position - 1;
  if (arrayIndex >= channelSnipes.length) {
    return errorEmbed("Snipe Out of Range", `Only the last **${channelSnipes.length}** deleted message(s) are stored in memory for this channel.`);
  }

  const target = channelSnipes[arrayIndex];
  const timestamp = Math.floor(new Date(target.deletedAt).getTime() / 1000);

  const embed = createEmbed()
    .setAuthor({
      name: target.authorTag,
      iconURL: target.authorAvatar,
    })
    .setDescription(target.content || "*[No text content — likely an image or embed]*")
    .addFields(
      { name: "Deleted", value: `<t:${timestamp}:R>`, inline: true },
      { name: "Position", value: `#${position} of ${channelSnipes.length}`, inline: true }
    )
    .setFooter({ text: `Requested position #${position}` })
    .setTimestamp(new Date(target.createdAt));

  if (target.attachment) {
    embed.setImage(target.attachment);
  }

  return embed;
}
